### ISSUE TITLE
Debug Impl for RustemonClient

### ISSUE THREAD

**Issue by c-git** [mlemesle/rustemon#19]
Hi,

Thanks for your work on this library. I'm just trying it out for the Shuttle Christmas Code Hunt and I encountered a challenge storing the RustemonClient in a OnceLock because it doesn't implement Debug. If it's not too much trouble and doesn't cause you any problems can you derive debug on this struct please (I won't need it anymore by the time you'd be able to do it but more for the next person).

Update: I realized the problem is with expect and unwrap on Result requiring Debug.

**Comment by mlemesle** [comment]
Hey there,

Thanks for reaching out ! Sorry for the late answer. I'll look into it right away
