### ISSUE TITLE
Serde Serialization Compatibility?

### ISSUE THREAD

**Issue by billy-briggs-dev** [mlemesle/rustemon#23]
Hey I'm using this wrapper for a small side project and was trying to convert the Pokemon struct to an object string. I noticed that the structs do not have compatibility with Serde Serialize, would it be possible to add that to the struct definitions for flexibility?

**Comment by billy-briggs-dev** [comment]
PR raised: #24

**Comment by mlemesle** [comment]
Hey there !

Thanks for using `rustemon`, and thanks for reaching. I appreciate it !

Regarding your needs, it sounds kinda specific to me. Most people, in my opinion, just wants to interact with PokeAPI, they wouldn't need to serialize anything.

With that in mind, do you think you can put the serialize implementations behind a feature gate called `serialize-models` that will be opt-out by default ?
Please let me know if you want to do it yourself or if you prefer me to do it.

**Comment by mlemesle** [comment]
Hey @billy-briggs-dev !

What do you think of my proposal ? Does that suit your needs ?
If so, do you want to implement or you rather want me to implement it ?

**Comment by mlemesle** [comment]
Closing the issue because no feedback
