### ISSUE TITLE
The doc build fails

### ISSUE THREAD

**Issue by gammelalf** [mlemesle/rustemon#9]
Hi, I was really excited about this clean wrapping of PokeAPI. Sadly your docs don't build.

Running `cargo doc` on my machine yielded a recursion overflow in the type checker.
Increasing the recursion limit fixed the problem for me.

Do you mind adding `#![recursion_limit = "256"]` to the crate?

**Comment by mlemesle** [comment]
Hi! Thanks for reaching out!
Indeed the docs don't seem to build. I missed it, nice catch !
Do you want to fix it and submit a PR or you prefer me to do it?
Feel free to contribute if you like.
Please let me know so I can do the fix if needed.
Have a good day!

**Comment by gammelalf** [comment]
Thanks for the quick response.
I'd prefer you to do it.
I don't think a PR is required for single line.

**Comment by mlemesle** [comment]
Well, there is no PR that is required for any project. It's just an opportunity to contribute.
But I understand, I'll fix it today and release a new version asap
